#!/usr/bin/env bash
# This Bash script configures a new Ubuntu machine to respect below requirements (this script will be run on the server itself).

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
