#!/usr/bin/env bash
# This script configure Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/;
        }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
