#!/usr/bin/env bash
# This configures Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/;
        }

        error_page 404 /404.html;
        location  /404 {
        root /var/www/html;
        internal;
        }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
