#!/usr/bin/env bash

# Checking for commit message

if [ -z "$1"  ]; then
    echo "Provide a commit message"
fi

# Adding changes

git add .
if [ $?  -ne 0 ]; then
    echo "Failed to add changes"
    exit 1
fi

# Commiting changes

git commit -m "$1"
if [ $?  -ne 0 ]; then
    echo "Failed to commit changes"
    exit 1
fi


# Pushing changes

git push
if [ $? -ne 0 ]; then
    echo "Failed to push changes"
    exit 1
fi

echo "Successfully added, commited and pushed changes"
