#!/usr/bin/env bash
# Bash script that configures Nginx so that its HTTP response contains a custom header "X-Served-By: $hostname"

sudo apt update
sudo apt -y install nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo 'Hello World!' > /var/www/html/index.html


echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root /var/www/html;
        index index.html index.htm;


        location /redirect_me {
                return 301 http://youtube.com/;
        }

        error_page 404 /404.html;
        location /404 {
                root /var/www/html;
                internal;
        }
}" > /etc/nginx/sites-available/default

sudo nginx -t

service nginx restart
