#!/usr/bin/env bash
# Bash script that installs and configures HAproxy on your lb-01 server, so that it send traffic to web-01 and web-02. Distribute requests using a roundrobin algorithm

apt-get -y update
apt-get -y install haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

echo "
frontend app
	bind *:80
	mode http
	default_backend app

backend app
	balance roundrobin
	server 184188-web-01 35.175.126.132:80 check
	server 184188-web-02 34.227.93.36:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
