#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.
mysqldump --all-databases -u root --password="$1" > backup.sql
today=$(date +"%d-%m-%y.tar.gz")
tar -czf "$today" backup.sql
