#!/usr/bin/env bash
# Bash script that takes commit message and push changes to github

if [ $# -ne 1 ]; then
    echo "Usage: $0 <commit message>"
    exit 1
fi

git add .; git commit -m $1; git push

echo "Successfully pushed changes to Github"
