#!/usr/bin/env bash
# Bash script that configures Nginx to listen to port 80 without running on all of a server's active IPv4's.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
