#!/usr/bin/env bash
# Bash script that accepts one argument

if [ $# -ne 1 ];  then
    echo "Usage $0 <commit message>"
    exit 1
fi


git add .; git commit -m "$1"; git push

echo "Changes successfully push to Github"
